### ISSUE TITLE
Code Open Source

### ISSUE THREAD

**Issue by newbie521** [LeoZhiheng/MTM-Tracker#1]
Is the author's code still open source?

**Comment by brytsknguyen** [comment]
Paper has been accepted and indexed. Please open source the code.

**Comment by LeoZhiheng** [comment]
Thank you for your attention. We will open the source code in two weeks.

**Comment by newbie521** [comment]
> Thank you for your attention. We will open the source code in two weeks.

Thanks

**Comment by LeoZhiheng** [comment]
> > Thank you for your attention. We will open the source code in two weeks.
> 
> Thanks

We have opened the source code. If you have any questions, please contact us.
Email: zhihengli@stumail.neu.edu.cn

**Comment by newbie521** [comment]
> > > Thank you for your attention. We will open the source code in two weeks.
> > 
> > 
> > Thanks
> 
> We have opened the source code. If you have any questions, please contact us. Email: [zhihengli@stumail.neu.edu.cn](mailto:zhihengli@stumail.neu.edu.cn)

Thank you very much for opening the source code. I have begun exploring it and hope to learn more details. Should I encounter any issues, I will contact you via email.

Thank you!
